export const ADD_TO_BAG = "ADD_TO_BAG";
export const REMOVE_FROM_BAG = "REMOVE_FROM_BAG";
export const SET_BAG_ITEMS_COUNT = "SET_BAG_ITEMS_COUNT";
export const RESET_BAG_ITEMS_COUNT = "RESET_BAG_ITEMS_COUNT";
